version: '3.8'

services:
  vault-a:
    image: vault:latest
    container_name: hcvault-a
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "8200:8200"
      - "8201:8201"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - hcvlt
  vault-b:
    image: vault:latest
    container_name: hcvault-b
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "8202:8200"
      - "8203:8201"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - hcvlt
networks:
  hcvlt:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.0.0/16